# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d37eb66ba5448563d7ab14dcae119ed612973a0b6010a0582afe9dff637753237d21efc4009e9788f96a1ddd33e6867ebd41ba1cd39effef25b859e8b0adcfa9

test:
  secret_key_base: f8b11280935b7f5adfaa8fd4c0bf357c970efaece8ef2ab5bcc49061adb6909f760212f3647d2c9a8d9d238df1cc27cbdcb32cfa419c13d05a3d5b090cae6106

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
